---
- name: Install QEMU KVM and virt-manager
  become: true
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
    state: latest

- name: Ensure libvirt group exists
  become: true
  group:
    name: libvirt
    state: present    

- name: Add current user to libvirt group
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    groups: libvirt
    append: yes

- debug:
    msg: "OBS!!! REBOOT NEEDED if first install"