---
- name: ensure Microsoft Edge GPG key added
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: ensure Microsoft repository added
  become: true  
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: ensure microsoft-edge-stable installed
  become: true
  apt:
    name: microsoft-edge-stable
    state: present