- name: ensure older versions of docker uninstalled
  become: true  
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent

- name: ensure ca-certificates, curl, gnupg, lsb-release installed
  become: true  
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: latest
    update_cache: true

- name: ensure docker's official GPG key added
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: ensure docker apt repository added
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes      

- name: ensure docker-ce docker-ce-cli containerd.io latest version installed
  become: true  
  apt:
    pkg:
    - docker-ce 
    state: latest
    update_cache: true

- debug:
    msg: "Verify that Docker Engine is installed correctly by running the hello-world image: sudo docker run hello-world"