---
- name: Ensure keychain latest version installed
  apt:
    name: keychain
    state: latest
  become: true

- name: Ensure keychain config in .bashrc
  blockinfile:
    path: ~/.bashrc
    marker_begin: "BEGIN keychain"
    marker_end: "END keychain"
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    block: |
      # keychain
      /usr/bin/keychain --nogui $HOME/.ssh/id_ed25519
      source $HOME/.keychain/$HOSTNAME-sh
