---
# FIXME: not idempotent
- name: download latest version of cheat from github
  get_url:
    url: https://github.com/cheat/cheat/releases/latest/download/cheat-linux-amd64.gz
    dest: ~/cheat-linux-amd64.gz
  become: true

- name: Extract .gz
  command: gzip -d ~/cheat-linux-amd64.gz
  become: true

- name: Change file ownership, group and permissions
  file:
    path: ~/cheat-linux-amd64
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Move to /usr/local/bin and rename to "cheat"
  command: mv ~/cheat-linux-amd64 /usr/local/bin/cheat
  become: true