---
  - name: Install apt-transport-https
    become: true
    ansible.builtin.apt:
      name: apt-transport-https
      state: latest
      update_cache: true

  - name: Add apt signing key
    become: true
    ansible.builtin.apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present

  - name: Add repository into sources list
    become: true
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
      state: present
      filename: microsoft-edge

  - name: Install microsoft-edge-stable
    become: true
    ansible.builtin.apt:
      name: "microsoft-edge-stable"
      state: latest
      update_cache: true