---
- name: Install flatpak
  become: true
  apt:
    name: flatpak
    state: present

- name: Add Flathub repository
  become: true
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install Slack from Flathub
  become: true
  command: flatpak install -y flathub com.slack.Slack