---
- name: Ensure packages installed
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - terminator
    - duplicity
    - vlc
    - vim
    - tree
    - tldr
    - snapd
    - htop
    - keepassxc
    - npm
    - p7zip-full
    - p7zip-rar
    - sshfs
    - python3-pip
    - fzf
    - chromium-browser
    - remmina
    - calibre
    - flameshot

- import_tasks: install-drawio.yml
- import_tasks: install-vscode.yml
#- import_tasks: install-ms-edge-debian.yml     # FIXME: doesn't work 15.8.2024, installed manually from https://www.microsoft.com/en-us/edge/business/download?form=MA13H4
- import_tasks: install-qemu-kvm-virt-manager.yml
- import_tasks: remove-obsolete-gnome-packages.yml
- import_tasks: install-slack.yml
- import_tasks: install-brave-browser.yml