---
- name: Ensure packages installed
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - terminator
    - duplicity
    - vlc
    - vim
    - tree
    - tldr  # update local cache: tldr -u (manual)
    - snapd
    - htop
    - keepassxc
    - npm
    - p7zip-full
    - p7zip-rar
    - sshfs
    - python3-pip
    - fzf
    - chromium-browser # TODO: plugins: bitwarden, privacy badger, uBlock origin, I don't care about cookies
    - remmina
    - calibre
    - flameshot

- import_tasks: install-drawio.yml
- import_tasks: install-vscode.yml
- import_tasks: install-ms-edge-debian.yml
- import_tasks: install-qemu-kvm-virt-manager.yml
- import_tasks: remove-obsolete-gnome-packages.yml
- import_tasks: install-slack.yml
- import_tasks: install-brave-browser.yml
- import_tasks: install-cheat.yml
- import_tasks: install-keychain.yml
- import_tasks: install-bat.yml
- import_tasks: install-neofetch.yml
- import_tasks: install-docker-ce.yml
- import_tasks: install-fish.yml
- import_tasks: install-postman-snapd.yml