---
- name: install cheat
  import_playbook: install-cheat.yml

- name: install fish
  import_playbook: install-fish.yml

- name: install keychain
  import_playbook: install-keychain.yml

- name: install neofetch
  import_playbook: install-neofetch.yml

- name: install docker-ce
  import_playbook: install-docker-ce.yml

- name: install docker-compose
  import_playbook: install-docker-compose.yml  