# 20201205
# tested: ubuntu20.04 (vagrantbox)
# ansible 2.9.6
---

- name: Ensure bat installed
  hosts: localhost
  tags: ['install-bat']
  tasks:

  - name: install bat
    apt:
      name: bat
      state: latest
    become: yes

  - name: create a symbolic link so can be runned as "bat" instead of "batcat"
    file:
      src: /usr/bin/batcat
      dest: /usr/local/bin/bat
      owner: root
      group: root
      state: link
    become: yes