# 20220609
---

- name: Set a hostname
  hosts: localhost
  vars:
    - my_hostname: default
  
  tasks:

  - name: assert my_hostname
    assert:
      that:
        - my_hostname != 'default'
      fail_msg: "'my_hostname' should not be 'default'"
      success_msg: "my_hostname ok, continue"

  - name: Set a hostname
    hostname:
      name:  "{{ my_hostname }}"
