# 20211230
# tested: popos 21.10
# ansible 2.10.8
---

- name: Install brave-browser (apt) # https://brave.com/linux/
  hosts: localhost
  tasks:

  - name: ensure apt-transport-https and curl latest versions installed
    become: true  
    apt:
      pkg:
      - apt-transport-https
      - curl
      state: latest
      update_cache: true

  - name: ensure brave-browser GPG key added
    become: true
    apt_key:
      url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
      state: present

  - name: ensure brave-browser apt repository added
    become: true
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
      state: present
      update_cache: yes          

  - name: ensure brave-browser latest version installed
    become: true  
    apt:
      name: brave-browser
      state: latest
      update_cache: true

  #TODO: install extensions