# 20201209
# tested: popos20.04, ubuntu20.04 (vagrantbox)
# ansible 2.9.6
---

- name: Install and config keychain (apt)
  hosts: localhost
  tasks:

  - name: Ensure keychain latest version installed
    apt:
      name: keychain
      state: latest
    become: yes

  - name: Ensure keychain config in .bashrc # FIXME
    blockinfile:
      path: ~/.bashrc
      marker_begin: "BEGIN keychain"
      marker_end: "END keychain"
      marker: "# {mark} ANSIBLE MANAGED BLOCK "
      block: |
        # keychain
        /usr/bin/keychain --nogui $HOME/.ssh/id_rsa
        source $HOME/.keychain/$HOSTNAME-sh
