---
- name: install bat
  import_playbook: install-bat.yml

- name: install cheat
  import_playbook: install-cheat.yml

- name: install fish
  import_playbook: install-fish.yml

- name: install keychain
  import_playbook: install-keychain.yml

- name: install neofetch
  import_playbook: install-neofetch.yml

- name: generate ssh-key (doesn't overwrite if exists)
  import_playbook: generate-ssh-key.yml    

- name: install vscode
  import_playbook: install-vscode-snapd.yml  

- name: install postman
  import_playbook: install-postman-snapd.yml

- name: install brave-browser
  import_playbook: install-brave-browser.yml

- name: install docker-ce
  import_playbook: install-docker-ce.yml

- name: install docker-compose
  import_playbook: install-docker-compose.yml  