---
- name: install bat
  import_playbook: install-bat.yml

- name: install cheat
  import_playbook: install-cheat.yml

- name: install fish
  import_playbook: install-fish.yml

- name: install keychain
  import_playbook: install-keychain.yml

- name: install neofetch
  import_playbook: install-neofetch.yml

- name: install tldr
  import_playbook: install-tldr.yml

- name: install vim
  import_playbook: install-vim.yml

- name: generate ssh-key (doesn't overwrite if exists)
  import_playbook: generate-ssh-key.yml    

- name: install tmux
  import_playbook: install-tmux.yml

- name: install snapd
  import_playbook: install-snapd.yml

- name: install vscode
  import_playbook: install-vscode-snapd.yml  