---
- name: install bat
  import_playbook: install-bat.yml

- name: install cheat
  import_playbook: install-cheat.yml

- name: install fish
  import_playbook: install-fish.yml

- name: install keychain
  import_playbook: install-keychain.yml

- name: install neofetch
  import_playbook: install-neofetch.yml

- name: install tldr
  import_playbook: install-tldr.yml

- name: install vim
  import_playbook: install-vim.yml  

# TODO: install snapd + vscode
# TODO: ssh-keygen -t ecdsa -b 521
# TODO: add .gitconfig